### ISSUE TITLE
Advise user to run opkg install ca-certificates

### ISSUE THREAD

**Issue by y0umu** [chuacw/DNS-over-HTTPS-for-OpenWRT#3]
Hi there, thank you for your nice work. If you are kindly enough to advise users to run
```
opkg update
opkg intall ca-certificates
```
things will be even better.

Why necessary? I checked the log, found something like this:
```
[2018-05-12 14:40:44] [ERROR] Get https://dns.cloudflare.com/dns-query?body=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&random_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: x509: failed to load system roots and no roots provided
```
This error is due to the dearth of ca-certificate which does not come by default with an official OpenWRT/LEDE firmware. Installing ca-certificate package will solve this.

**Comment by chuacw** [comment]
This isn't right. I don't have ca-certificates package installed and I don't have this problem.
You might need to do further research.

**Comment by y0umu** [comment]
Sorry if I have missed point. But it really works for **me** after I googled around with key words "openwrt  x509: failed to load system roots and no roots provided" and I was inspired by [this](https://caddy.community/t/activating-privacy-features-failed/2566/5) thread.

**Comment by chuacw** [comment]
And it worked for me without the ca-certificates.
